Add Dependabot explanation
hsf-training/hsf-training-cicd-github pull request #48
Opened 2023-01-24 03:49 UTC by amanmdesai

Closes #41

2023-01-24 15:48 UTC, klieret commented
We should add links to the dependabot docs and an example of the config for github actions, e.g. [mine](https://github.com/klieret/python-cookiecutter/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/dependabot.yml) and tell them where to place it

2023-01-24 15:59 UTC, amanmdesai commented
Hi thanks. 

I have updated the file. Could please check again?

2023-01-24 16:14 UTC, klieret requested changes

2023-01-24 16:14 UTC, klieret commented on _episodes/08-adding-ci-to-your-code.md
> +The dependabot action can be added to a Github repository by creating file `dependabot.yml` in the `.github/` folder. The content of the file looks like this:
the file

2023-01-24 16:14 UTC, klieret commented on _episodes/08-adding-ci-to-your-code.md
> +For more information on Dependabot, see e.g., [LINK](https://docs.github.com/en/code-security/dependabot)
LINK -> here?

2023-01-24 16:14 UTC, klieret commented on _episodes/08-adding-ci-to-your-code.md
> +For more information on Dependabot, see e.g., [LINK](https://docs.github.com/en/code-security/dependabot)
also missing full stop

2023-01-24 16:16 UTC, amanmdesai commented on _episodes/08-adding-ci-to-your-code.md
> +The dependabot action can be added to a Github repository by creating file `dependabot.yml` in the `.github/` folder. The content of the file looks like this:
done

2023-01-24 16:16 UTC, amanmdesai commented on _episodes/08-adding-ci-to-your-code.md
> +For more information on Dependabot, see e.g., [LINK](https://docs.github.com/en/code-security/dependabot)
done

2023-01-24 16:45 UTC, amanmdesai commented
Hi @klieret Implemented the changes

2023-01-25 00:19 UTC, klieret approved these changes
Thanks!

2023-01-25 00:19 UTC, merged

2023-01-25 00:20 UTC, klieret commented
@all-contributors please add @amanmdesai  for content